$(function(){
	var categoryItem = $('.nav-category .category-item');
	var str1 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
		
	var str2 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+				'<a class="btn btn-buy" href="#">选购</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str3 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/ds.jpg" />'
		+				'<span class="text">小米电视 43英寸</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/ds.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'</ul>'
		+	'</div>';
	
	var str4 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/l.jpg" />'
		+				'<span class="text">米家扫地机器人及配件</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/ds.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	
	var str5 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/dianyuan.jpg" />'
		+				'<span class="text">小米移动电源</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/ds.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str6 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/headphone.jpg" />'
		+				'<span class="text">小米头戴式耳机</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/ds.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/n3-1.jpg" />'
		+				'<span class="text">小米手机5</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/bijiben80.jpg" />'
		+				'<span class="text">小米笔记本Air</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str7 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/tiemo.jpg" />'
		+				'<span class="text">贴膜</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/tiemo.jpg" />'
		+				'<span class="text">贴膜</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/tiemo.jpg" />'
		+				'<span class="text">贴膜</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/tiemo.jpg" />'
		+				'<span class="text">贴膜</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str8 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiancai.jpg" />'
		+				'<span class="text">线材</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiancai.jpg" />'
		+				'<span class="text">线材</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiancai.jpg" />'
		+				'<span class="text">线材</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiancai.jpg" />'
		+				'<span class="text">线材</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str9 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiangbao.jpg" />'
		+				'<span class="text">箱包</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiangbao.jpg" />'
		+				'<span class="text">箱包</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/xiangbao.jpg" />'
		+				'<span class="text">箱包</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	var str10 = '<div class="children clearfix">'
		+		'<ul class="children-list clearfix">'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/mitu.jpg" />'
		+				'<span class="text">米兔玩偶</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/mitu.jpg" />'
		+				'<span class="text">米兔玩偶</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/mitu.jpg" />'
		+				'<span class="text">米兔玩偶</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/mitu.jpg" />'
		+				'<span class="text">米兔玩偶</span>'
		+				'</a>'
		+			'</li>'
		+			'<li class="star-goods"><a class="link" href="#">'
		+				'<img class="thumb" src="img/mitu.jpg" />'
		+				'<span class="text">米兔玩偶</span>'
		+				'</a>'
		+			'</li>'
		+		'</ul>'
		+	'</div>';
	
	
	
		categoryItem.parent().hover(function(){
			$(this).parent().css({width:'1228px'});
		},function(){
			$(this).parent().css({width:''});
		});
		//console.log(categoryItem.parent());
	
		categoryItem.eq(0).hover(function(){
			$(this).append(str1);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(1).hover(function(){
			$(this).append(str2);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(2).hover(function(){
			$(this).append(str3);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(3).hover(function(){
			$(this).append(str4);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(4).hover(function(){
			$(this).append(str5);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(5).hover(function(){
			$(this).append(str6);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(6).hover(function(){
			$(this).append(str7);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(7).hover(function(){
			$(this).append(str8);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(8).hover(function(){
			$(this).append(str9);
		},function(){
			$(this).find('.children').remove();
		});
		categoryItem.eq(9).hover(function(){
			$(this).append(str10);
		},function(){
			$(this).find('.children').remove();
		});
	
});




